WIP: Pi calculations
carpentries-incubator/hpc-intro pull request #275
Opened 2021-02-08 01:20 UTC by mikerenfro

Some additional materials related to testing Python MPI code. General review requested, and I'll wait until the sprawling curriculum updates have been merged before touching anything outside this folder.

Baseline serial data showing scaling with respect to problem size can be generated with something like:

```
for n in 1 2 4 8 16 32 64 128 256 512 ; do ./pi-serial.py ${n}000000; done > pi-serial.txt
```

where the values of `n` should get large enough to not run out of memory on the designated computer, but large enough to take several seconds to complete.

After the largest problem size for the serial case has been determined, the MPI performance data can be generated with something like:

```
for n in 1 2 4 8 16 28 56 84 112; do mpirun -np ${n} ./pi-mpi.py 512000000 | tail -n 1; done > pi-mpi.txt
```

These files can then be compared with: `./pi-plot-parallel-results.py pi-mpi.txt pi-serial.txt`, which will generate both elapsed time graphs and a more interesting speedup graph as attached.

HPC, with up to 4 28-core nodes. shows relatively consistent speedup through 3 nodes:
![mpi_Speedup_factor](https://user-images.githubusercontent.com/1451881/107165110-77fc9a00-6977-11eb-80d7-5f3fefe9c873.png)

8-core Laptop, shows the expected diminishing return once all 8 cores are in use:
![laptop-mpi_Speedup_factor](https://user-images.githubusercontent.com/1451881/107165212-d4f85000-6977-11eb-8b92-3e3682a6e72b.png)

Initial conclusions that might be useful to include in lessons:

- both graphs show considerable overhead for MPI on small core counts
- some newer laptops may be faster than some older HPCs for small core counts

2021-02-08 15:01 UTC, reid-a commented
Thanks Mike, this is important to convey!

In the second figure, the first data point for one core is below "1" on the Y-axis, "speed-up factor". Is there a reason for this? If I had to guess, I'd guess you're actually measuring speed, and there's a secret other Y-axis that's not in the figure?  But for the purpose of the narrative we're trying to convey, it would be good if these were aligned. (Maybe this is fixed in the subsequent commits below the figure?)

2021-02-08 16:42 UTC, mikerenfro commented
> Thanks Mike, this is important to convey!
> 
> In the second figure, the first data point for one core is below "1" on the Y-axis, "speed-up factor". Is there a reason for this? If I had to guess, I'd guess you're actually measuring speed, and there's a secret other Y-axis that's not in the figure? But for the purpose of the narrative we're trying to convey, it would be good if these were aligned. (Maybe this is fixed in the subsequent commits below the figure?)

Honestly, the 2-core runs are probably under 1.0 on the y axis as well. I assume this is due to MPI setup and teardown overhead. But I'll take a second look and make sure my speedups aren't miscalculated (they should be using the serial version of the Pi calculator for the given problem size as the baseline time).

2021-02-08 17:29 UTC, mikerenfro commented
Found an off-by-one on finding my baseline time, so no real MPI overhead as I'd first thought.

Laptop:
![laptop-mpi_Speedup_factor](https://user-images.githubusercontent.com/1451881/107257757-a5d9f100-6a00-11eb-8dfe-2d6a23afb217.png)

HPC:
![hpc-mpi_Speedup_factor](https://user-images.githubusercontent.com/1451881/107257848-bb4f1b00-6a00-11eb-902b-87b4ea2fca38.png)

2021-02-08 18:06 UTC, tkphd commented
Please use the `locale` package to format the numbers with grouping. The general idea is 

```python
import locale
locale.setlocale(l10n.LC_ALL, "")

...

plt.title("MPI π results with {:n} samples".format(512000000000))
```

This should result in the title being a more legible **MPI π results with 512,000,000,000 samples**.
If the library works the way I hope, then for those preferring '.' as their grouping delimiter, it will automatically generate "MPI π results with 512.000.000.000 samples" instead. Note that, since GitHub is 'murican, it will always use ','.

2021-02-10 00:39 UTC, tkphd requested changes
Please place images under /fig instead of /files, and create entries for them in _includes/all_figures.html.

2021-02-10 00:42 UTC, tkphd commented
"allone" variable name triggers a spellchecker error. Consider underscores or camel case to try clearing it.

2021-02-10 04:59 UTC, mikerenfro commented
> "allone" variable name triggers a spellchecker error. Consider underscores or camel case to try clearing it.

Can't underscore a macro name, but in modifying the code to match the Python variable names, `all` is no longer relevant.

Initialize:
![initialize](https://user-images.githubusercontent.com/1451881/107466786-47a92d00-6b2a-11eb-8d37-4dc595b17cb9.png)

Scatter 1:
![scatter-1](https://user-images.githubusercontent.com/1451881/107466798-4d9f0e00-6b2a-11eb-9c30-ebde13c6fa8c.png)

Scatter 2:
![scatter-2](https://user-images.githubusercontent.com/1451881/107466815-5394ef00-6b2a-11eb-9176-ab51c259e737.png)

Compute:
![compute](https://user-images.githubusercontent.com/1451881/107466827-58f23980-6b2a-11eb-90b1-934678b2e118.png)

Gather:
![gather](https://user-images.githubusercontent.com/1451881/107466855-627ba180-6b2a-11eb-82a2-6e30ae112fbb.png)

Finalize:
![finalize](https://user-images.githubusercontent.com/1451881/107466874-6a3b4600-6b2a-11eb-8ad8-3d6688dc918f.png)

2021-02-10 17:33 UTC, tkphd approved these changes

2021-02-10 17:37 UTC, merged

2021-02-10 17:43 UTC, tkphd requested changes

2021-02-10 17:43 UTC, tkphd commented on files/pi-mpi.py
> +        pi_specific = np.float32(3.141592653589793238462643383279502884197169)
float32 truncates this to `3.1415927410125732421875`.
Use `np.pi` instead.

2021-02-10 17:43 UTC, tkphd commented on files/pi-mpi-hpc.txt
> +1,512000000,5859.375000,28.546736,0.003635
- These `pi-*.txt` files represent CSV data. Please change their extensions and add header rows.
- Are these files to be used in the lesson? If not, consider bundling the results, and plot generator scripts, in a tarball.

2021-02-10 17:44 UTC, tkphd commented
Ack, I meant to approve the changes requested, only, not the entire PR. Oops!