Fixed setup page link to XQuartz.
carpentries-incubator/hpc-intro pull request #358
Opened 2021-05-24 00:03 UTC by amfage

A very minor fix - the link to XQuartz was missing the http://
This is my first pull request to a Carpentries project so I hope it's OK!

2021-05-24 13:55 UTC, mikerenfro requested changes
Correct, and thanks. If you could change that to an `https` instead of `http`, should be able to merge that in shortly.

2021-05-24 23:23 UTC, amfage commented
Hi, I've changed the links to https in the setup page and checked that they work.

2021-05-26 01:55 UTC, mikerenfro approved these changes

2021-05-26 02:02 UTC, merged

2021-05-26 02:04 UTC, mikerenfro commented
Looks good, and merged. In the future, making a new branch separate from `gh-pages` will make contributions easier, but that’s not affecting this PR. Thanks.